version: '3.8'

services:
  app:
    build: .
    container_name: myapp
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_URL: jdbc:postgresql://db:5432/library_db
      DB_USER: postgres
      DB_PASSWORD: 1395
      DB_DRIVER: org.postgresql.Driver
      DB_POOL_SIZE: 10
      DB_POOL_MIN_IDLE: 2
    volumes:
      - ./.m2:/root/.m2
    networks:
      - app-network

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: library_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1395
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge